apiVersion: v1
kind: Service
metadata:
  name: {{ include "ortelius-www.name" . }}
  labels:
  {{- range $key, $val := .Values.keptnLabels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
spec:
  selector:
    app: {{ include "ortelius-www.name" . }}
    tier: backend
  ports:
    - name: www
      protocol: TCP
      port: 80
      targetPort: 80
