replicaCount: 1
service:
  serviceMonitor:
    enabled: true
ingress:
  enabled: true
  addDefaultBackend: true
  host: ortelius.io
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
image:
  repository: quay.io/ortelius/website
  tag: main-v10.0.9-g40dbad
  sha: sha256:a809ff40d1766e7486e019d55e0712899799f552aae4cacf0cae1dedd2cf139d
  pullPolicy: Always
keptnLabels:
  keptnProject: ortelius
  keptnService: website
  keptnStage: prd
