replicaCount: 1
service:
  serviceMonitor:
    enabled: true
ingress:
  enabled: true
  addDefaultBackend: true
  host: ortelius.io
  path: /
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    backstage.io/kubernetes-id: ortelius-www
image:
  repository: quay.io/ortelius/website
  tag: main-v10.0.19-g6983a6
  sha: sha256:04dc7b8e478c392e7bdd0d45423a3ec71ef29105fdf612078b83cc856b59f704
  pullPolicy: Always
keptnLabels:
  keptnProject: ortelius
  keptnService: website
  keptnStage: prd
