replicaCount: 1
service:
  serviceMonitor:
    enabled: true
ingress:
  enabled: true
  addDefaultBackend: true
  host: ortelius.io
  path: /
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    backstage.io/kubernetes-id: ortelius-www
image:
  repository: quay.io/ortelius/website
  tag: main-v10.0.12-g0c028b
  sha: sha256:1a24efd3012056c1c18285753c0cdb1b13cfa41c6d3ab2a699e3eb3a67528d02
  pullPolicy: Always
keptnLabels:
  keptnProject: ortelius
  keptnService: website
  keptnStage: prd
