replicaCount: 1
service:
  serviceMonitor:
    enabled: true
ingress:
  enabled: true
  addDefaultBackend: true
  host: ortelius.io
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
image:
  repository: quay.io/ortelius/website
  tag: main-v10.0.5-gd06d3b
  sha: sha256:4e67a7797ec654827457df5a972ac13d4d346909b1d87aee39d9533cd23255a3
  pullPolicy: Always
keptnLabels:
  keptnProject: ortelius
  keptnService: website
  keptnStage: prd
