replicaCount: 1
service:
  serviceMonitor:
    enabled: true
ingress:
  enabled: true
  addDefaultBackend: true
  host: ortelius.io
  path: /
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    backstage.io/kubernetes-id: ortelius-www
image:
  repository: quay.io/ortelius/website
  tag: main-v10.0.18-g4855e0
  sha: sha256:6b530f854c7afa618d0ac20cca26a1cb24c86207f705b04b0e23e55c6c47990e
  pullPolicy: Always
keptnLabels:
  keptnProject: ortelius
  keptnService: website
  keptnStage: prd
